### ISSUE TITLE
Weird text splitting

### ISSUE THREAD

**Issue by JorikSchellekens** [matrix-org/matrix.to#112]
![image](https://user-images.githubusercontent.com/23084468/93495852-7d910f00-f906-11ea-8b93-932098d4f4b9.png)
![image](https://user-images.githubusercontent.com/23084468/93495867-81249600-f906-11ea-80bc-5b17ee4ba7a2.png)

**Comment by MazeChaZer** [comment]
The issue is caused by this CSS fragment, would be interesting to know why it's there and if it can be removed.

```css
.createLinkTile h1 {
    word-break: break-all;
}
```
